apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: blood-donation
  labels:
    app: shared
    component: security
type: Opaque
data:
  # DB_PASSWORD: "bloodpass" (base64 encoded)
  DB_PASSWORD: Ymxvb2RwYXNz
  # JWT_SECRET: "blood-jwt-secret-2024" (base64 encoded)
  JWT_SECRET: Ymxvb2Qtand0LXNlY3JldC0yMDI0
  # ADMIN_JWT_SECRET: "admin-jwt-secret-2024" (base64 encoded)
  ADMIN_JWT_SECRET: YWRtaW4tand0LXNlY3JldC0yMDI0
