apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: blood-donation-data
  labels:
    app: mysql
    component: database
    tier: data
type: Opaque
data:
  # root-password: "bloodadmin123" (base64 encoded)
  root-password: Ymxvb2RhZG1pbjEyMw==
  # user-password: "bloodpass" (base64 encoded)
  user-password: Ymxvb2RwYXNz
