apiVersion: v1
kind: Service
metadata:
  name: appointment-service
  namespace: blood-donation
  labels:
    app: appointment-service
    component: api
    tier: backend
spec:
  selector:
    app: appointment-service
  ports:
  - port: 3003
    targetPort: 3003
    protocol: TCP
    name: http
  type: ClusterIP
