apiVersion: v1
kind: Service
metadata:
  name: campaign-service
  namespace: blood-donation
  labels:
    app: campaign-service
    component: api
    tier: backend
spec:
  selector:
    app: campaign-service
  ports:
  - port: 3002
    targetPort: 3002
    protocol: TCP
    name: http
  type: ClusterIP
