apiVersion: v1
kind: Namespace
metadata:
  name: blood-donation-data
  labels:
    environment: production
    project: blood-donation
    tier: data
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/audit: privileged
  annotations:
    kubernetes.io/managed-by: "devops-team"
